# Allows admins to bypass protection signs
allow-admin-bypass: true
# Allows admins to break protection signs
allow-admin-break: true
# Admins will silently open containers when peeking into a protected container
admin-silent-snoop: true
# Protected blocks are not affected by explosions
explosion-protection: true
# Doors are able to be protected
door-protection: true
# Containers are able to be protected
container-protection: true
# Errors messages will be shown to users.
enable-error-messages: true
# Sends a message to players when protectable blocks are placed.
enable-hints: true
