# Allows admins to bypass protection signs
allow-admin-bypass: true
# Allows admins to break protection signs
allow-admin-break: true
# Protected blocks are not affected by explosions
explosion-protection: true
# Doors are able to be protected
door-protection: true
# Errors messages will be shown to users.
enable-error-messages: true
# Sends a message to players when protectable blocks are placed.
enable-hints: true
# Players in creative can override all permissions.
creative-override: true